version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: iam_postgres
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam_network

  redis:
    image: redis:7-alpine
    container_name: iam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iam_network

volumes:
  postgres_data:
  redis_data:

networks:
  iam_network:
    driver: bridge